### ISSUE TITLE
Hydration issues on /minting

### ISSUE THREAD

**Issue by MSBivens** [NudeClub/NudeClubMVP#1] opened 2022-11-21 22:32 UTC
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

**Comment by turingblocks** [comment] 2022-12-15 00:15
I believe this was caused by <h1> tags within <h1> tags caused different output. error no longer presents.

**Comment by turingblocks** [comment] 2022-12-15 03:42
closing issue as resolved

**Closed by turingblocks** 2022-12-15 03:42 UTC
Labels: enhancement
